import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Lang = "en" | "hi" | "mr";

export const LANGUAGES: { code: Lang; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिंदी" },
  { code: "mr", label: "Marathi", native: "मराठी" },
];

const LANG_KEY = "dqa_lang";

// ============================================================
// Translation dictionary — one key per user-facing UI string.
// AI-generated answers are translated separately by asking Gemini
// to respond in the selected language (see api.ts `language` param);
// this dictionary only covers static chrome text.
// ============================================================
const translations: Record<Lang, Record<string, string>> = {
  en: {
    appName: "DataQuery Agent",
    tagline: "Ask questions in English. Get answers, tables, and charts.",
    featurePostgres: "Postgres",
    featureGemini: "Gemini SQL",
    featureCharts: "Auto charts",
    signInWithGoogle: "Sign in with Google",
    or: "or",
    fullName: "Full name",
    emailAddress: "Email address",
    password: "Password (min 8 characters)",
    createAccount: "Create account",
    signIn: "Sign in",
    haveAccount: "Already have an account? Sign in",
    newHere: "New here? Create an account",
    continueAsGuest: "Continue as Guest",
    guestHint: "Try 2 real questions on live data — no account needed.",
    verifying: "Verifying your account…",
    footerNote1: "Your queries run read-only against your warehouse.",
    footerNote2: "Destructive SQL is blocked by the agent.",
    newChat: "New Chat",
    conversations: "Conversations",
    noConversations: "No conversations yet.",
    startOneAbove: "Start one above ✨",
    rename: "Rename",
    delete: "Delete",
    queryHistory: "Query History",
    settings: "Settings",
    signOut: "Log out",
    guestBannerTitle: "Guest mode",
    guestBannerBody: "Conversations aren't saved. Sign in to keep your history.",
    guestPromptsLeft: "prompts left",
    guestLimitReached: "You've used your free guest prompts.",
    guestSignInToContinue: "Sign in to keep chatting.",
    askAnything: "Ask me anything about your sales data",
    askSubtitle:
      "I translate plain English into safe, read-only SQL, run it, and visualize the result.",
    exampleTop5: "Show me the top 5 products by revenue",
    exampleAvgPrice: "What's the average unit price by category?",
    exampleTrend: "Show monthly sales trends",
    exampleTopCategory: "Which category has the most sales?",
    inputPlaceholder: "Ask anything about your data…",
    thinking: "Thinking… generating SQL with Gemini",
    inputFooter:
      "Enter to send · Shift+Enter for a new line · Results are AI-generated, verify before acting",
    generatedByGemini: "DataQuery Agent · generated by Gemini",
    viewSql: "View SQL",
    hideSql: "Hide SQL",
    copy: "Copy",
    copied: "Copied",
    rows: "rows",
    row: "row",
    resultSet: "Result set",
    copyCsv: "Copy CSV",
    copiedCsv: "Copied CSV",
    noRowsReturned: "No rows returned",
    switchConversation: "Switch conversation…",
    newConversation: "New conversation",
    noMatchingConversations: "No matching conversations",
    queryDetail: "Query detail",
    noQueriesYet: "No queries executed yet.",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    language: "Language",
    close: "Close",
    queryFailed: "Query failed",
    settingsTabGeneral: "General",
    settingsTabUpgrade: "Upgrade",
    currentPlan: "Current plan",
    upgradeNow: "Upgrade",
    mostPopular: "Most popular",
    perMonth: "/month",
    upgradeDemoNote: "Demo only — no real payment is taken.",
    upgradeClickToast: "This is a demo — upgrades aren't available yet.",
    selectConversations: "Select conversations",
    selected: "selected",
    cancel: "Cancel",
    forgotPassword: "Forgot password?",
    resetPassword: "Reset password",
    newPassword: "New password (min 8 characters)",
    sendResetLink: "Reset password",
    backToSignIn: "Back to sign in",
    resetPasswordHint: "Enter your account email and choose a new password.",
  },
  hi: {
    appName: "DataQuery Agent",
    tagline: "अंग्रेज़ी में सवाल पूछें। जवाब, टेबल और चार्ट पाएं।",
    featurePostgres: "Postgres",
    featureGemini: "Gemini SQL",
    featureCharts: "ऑटो चार्ट",
    signInWithGoogle: "Google से साइन इन करें",
    or: "या",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड (कम से कम 8 अक्षर)",
    createAccount: "खाता बनाएं",
    signIn: "साइन इन करें",
    haveAccount: "पहले से खाता है? साइन इन करें",
    newHere: "नए हैं? खाता बनाएं",
    continueAsGuest: "गेस्ट के रूप में जारी रखें",
    guestHint: "लाइव डेटा पर 2 असली सवाल आज़माएं — खाते की ज़रूरत नहीं।",
    verifying: "आपका खाता जांचा जा रहा है…",
    footerNote1: "आपकी क्वेरी केवल पढ़ने के लिए आपके डेटा पर चलती हैं।",
    footerNote2: "नुकसानदायक SQL को एजेंट द्वारा रोका जाता है।",
    newChat: "नई चैट",
    conversations: "बातचीत",
    noConversations: "अभी तक कोई बातचीत नहीं।",
    startOneAbove: "ऊपर से एक शुरू करें ✨",
    rename: "नाम बदलें",
    delete: "हटाएं",
    queryHistory: "क्वेरी इतिहास",
    settings: "सेटिंग्स",
    signOut: "लॉग आउट",
    guestBannerTitle: "गेस्ट मोड",
    guestBannerBody: "बातचीत सेव नहीं होगी। इतिहास रखने के लिए साइन इन करें।",
    guestPromptsLeft: "प्रॉम्प्ट बचे हैं",
    guestLimitReached: "आपके मुफ्त गेस्ट प्रॉम्प्ट खत्म हो गए हैं।",
    guestSignInToContinue: "चैट जारी रखने के लिए साइन इन करें।",
    askAnything: "अपने सेल्स डेटा के बारे में कुछ भी पूछें",
    askSubtitle:
      "मैं सामान्य अंग्रेज़ी को सुरक्षित, केवल-पढ़ने वाले SQL में बदलता हूं, उसे चलाता हूं, और परिणाम को विज़ुअलाइज़ करता हूं।",
    exampleTop5: "राजस्व के हिसाब से टॉप 5 प्रोडक्ट दिखाएं",
    exampleAvgPrice: "श्रेणी के अनुसार औसत यूनिट कीमत क्या है?",
    exampleTrend: "मासिक बिक्री रुझान दिखाएं",
    exampleTopCategory: "किस श्रेणी की सबसे ज़्यादा बिक्री है?",
    inputPlaceholder: "अपने डेटा के बारे में कुछ भी पूछें…",
    thinking: "सोच रहा है… Gemini से SQL बना रहा है",
    inputFooter:
      "भेजने के लिए Enter · नई लाइन के लिए Shift+Enter · परिणाम AI-जनित हैं, कार्रवाई से पहले जांच लें",
    generatedByGemini: "DataQuery Agent · Gemini द्वारा जनरेट किया गया",
    viewSql: "SQL देखें",
    hideSql: "SQL छुपाएं",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया",
    rows: "पंक्तियां",
    row: "पंक्ति",
    resultSet: "परिणाम सेट",
    copyCsv: "CSV कॉपी करें",
    copiedCsv: "CSV कॉपी हो गया",
    noRowsReturned: "कोई पंक्ति नहीं मिली",
    switchConversation: "बातचीत बदलें…",
    newConversation: "नई बातचीत",
    noMatchingConversations: "कोई मेल खाती बातचीत नहीं",
    queryDetail: "क्वेरी विवरण",
    noQueriesYet: "अभी तक कोई क्वेरी नहीं चली।",
    appearance: "थीम",
    light: "लाइट",
    dark: "डार्क",
    language: "भाषा",
    close: "बंद करें",
    queryFailed: "क्वेरी विफल हुई",
    settingsTabGeneral: "सामान्य",
    settingsTabUpgrade: "अपग्रेड",
    currentPlan: "मौजूदा प्लान",
    upgradeNow: "अपग्रेड करें",
    mostPopular: "सबसे लोकप्रिय",
    perMonth: "/माह",
    upgradeDemoNote: "सिर्फ डेमो — कोई असली भुगतान नहीं लिया जाता।",
    upgradeClickToast: "यह एक डेमो है — अपग्रेड अभी उपलब्ध नहीं है।",
    selectConversations: "बातचीत चुनें",
    selected: "चयनित",
    cancel: "रद्द करें",
    forgotPassword: "पासवर्ड भूल गए?",
    resetPassword: "पासवर्ड रीसेट करें",
    newPassword: "नया पासवर्ड (कम से कम 8 अक्षर)",
    sendResetLink: "पासवर्ड रीसेट करें",
    backToSignIn: "साइन इन पर वापस जाएं",
    resetPasswordHint: "अपना खाता ईमेल डालें और नया पासवर्ड चुनें।",
  },
  mr: {
    appName: "DataQuery Agent",
    tagline: "इंग्रजीत प्रश्न विचारा. उत्तरं, टेबल आणि चार्ट मिळवा.",
    featurePostgres: "Postgres",
    featureGemini: "Gemini SQL",
    featureCharts: "ऑटो चार्ट",
    signInWithGoogle: "Google ने साइन इन करा",
    or: "किंवा",
    fullName: "पूर्ण नाव",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड (किमान 8 अक्षरे)",
    createAccount: "खाते तयार करा",
    signIn: "साइन इन करा",
    haveAccount: "आधीच खाते आहे? साइन इन करा",
    newHere: "नवीन आहात? खाते तयार करा",
    continueAsGuest: "पाहुणे म्हणून सुरू ठेवा",
    guestHint: "लाइव्ह डेटावर 2 खरे प्रश्न वापरून पहा — खाते लागत नाही.",
    verifying: "तुमचे खाते तपासले जात आहे…",
    footerNote1: "तुमच्या क्वेरी फक्त वाचनासाठी तुमच्या डेटावर चालतात.",
    footerNote2: "हानिकारक SQL एजंटद्वारे अडवले जाते.",
    newChat: "नवीन चॅट",
    conversations: "संभाषणे",
    noConversations: "अजून कोणतेही संभाषण नाही.",
    startOneAbove: "वर एक सुरू करा ✨",
    rename: "नाव बदला",
    delete: "काढा",
    queryHistory: "क्वेरी इतिहास",
    settings: "सेटिंग्ज",
    signOut: "लॉग आउट",
    guestBannerTitle: "पाहुणे मोड",
    guestBannerBody: "संभाषणे जतन होणार नाहीत. इतिहास ठेवण्यासाठी साइन इन करा.",
    guestPromptsLeft: "प्रॉम्प्ट शिल्लक",
    guestLimitReached: "तुमचे मोफत पाहुणे प्रॉम्प्ट संपले आहेत.",
    guestSignInToContinue: "चॅट सुरू ठेवण्यासाठी साइन इन करा.",
    askAnything: "तुमच्या विक्री डेटाबद्दल काहीही विचारा",
    askSubtitle:
      "मी सोपी इंग्रजी सुरक्षित, फक्त-वाचनीय SQL मध्ये रूपांतरित करतो, ती चालवतो, आणि निकाल दाखवतो.",
    exampleTop5: "महसुलानुसार टॉप 5 उत्पादने दाखवा",
    exampleAvgPrice: "श्रेणीनुसार सरासरी युनिट किंमत किती आहे?",
    exampleTrend: "मासिक विक्री कल दाखवा",
    exampleTopCategory: "कोणत्या श्रेणीची विक्री सर्वाधिक आहे?",
    inputPlaceholder: "तुमच्या डेटाबद्दल काहीही विचारा…",
    thinking: "विचार करत आहे… Gemini सह SQL तयार करत आहे",
    inputFooter:
      "पाठवण्यासाठी Enter · नवीन ओळीसाठी Shift+Enter · निकाल AI-निर्मित आहेत, कृती करण्यापूर्वी तपासा",
    generatedByGemini: "DataQuery Agent · Gemini द्वारे तयार",
    viewSql: "SQL पहा",
    hideSql: "SQL लपवा",
    copy: "कॉपी करा",
    copied: "कॉपी झाले",
    rows: "ओळी",
    row: "ओळ",
    resultSet: "निकाल संच",
    copyCsv: "CSV कॉपी करा",
    copiedCsv: "CSV कॉपी झाले",
    noRowsReturned: "कोणत्याही ओळी सापडल्या नाहीत",
    switchConversation: "संभाषण बदला…",
    newConversation: "नवीन संभाषण",
    noMatchingConversations: "जुळणारे संभाषण नाही",
    queryDetail: "क्वेरी तपशील",
    noQueriesYet: "अजून कोणतीही क्वेरी चालवली नाही.",
    appearance: "थीम",
    light: "लाइट",
    dark: "डार्क",
    language: "भाषा",
    close: "बंद करा",
    queryFailed: "क्वेरी अयशस्वी झाली",
    settingsTabGeneral: "सामान्य",
    settingsTabUpgrade: "अपग्रेड",
    currentPlan: "सध्याची योजना",
    upgradeNow: "अपग्रेड करा",
    mostPopular: "सर्वाधिक लोकप्रिय",
    perMonth: "/महिना",
    upgradeDemoNote: "फक्त डेमो — कोणतेही खरे पेमेंट घेतले जात नाही.",
    upgradeClickToast: "ही एक डेमो आहे — अपग्रेड अजून उपलब्ध नाही.",
    selectConversations: "संभाषणे निवडा",
    selected: "निवडलेले",
    cancel: "रद्द करा",
    forgotPassword: "पासवर्ड विसरलात?",
    resetPassword: "पासवर्ड रीसेट करा",
    newPassword: "नवीन पासवर्ड (किमान 8 अक्षरे)",
    sendResetLink: "पासवर्ड रीसेट करा",
    backToSignIn: "साइन इनवर परत जा",
    resetPasswordHint: "तुमचा खाते ईमेल टाका आणि नवीन पासवर्ड निवडा.",
  },
};

interface LanguageState {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: keyof (typeof translations)["en"]) => string;
}

const LanguageContext = createContext<LanguageState | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem(LANG_KEY);
    return stored === "hi" || stored === "mr" || stored === "en" ? stored : "en";
  });

  useEffect(() => {
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = useCallback((l: Lang) => setLangState(l), []);

  const t = useCallback(
    (key: keyof (typeof translations)["en"]) =>
      translations[lang][key] ?? translations.en[key] ?? String(key),
    [lang]
  );

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageState {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
